export default function(){
    return[
        {
            id: 1,
            title: 'Pulp Fiction',
            description : "L'odyssée sanglante et burlesque de petits malfrats dans la jungle de Hollywood à travers trois histoires qui s'entremêlent.",
            genre: ['Action','Thriller','Horror'],
            release_date: 1994,
            director: 'Quentin Tarantino',
            actors: 'John Travolta, Samuel L. Jackson, Uma Thurman',
            cover : 'http://www.retourverslecinema.com/wp-content/uploads/2013/09/Pulp-fiction-1994.jpg',
            upload_date: 19950326,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=Sob95vSNeeQ',
            downloadtime: 'Downloaded 789 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        },
        {
            id: 2,
            title: 'Pusher',
            description : "A Copenhague, Frank vend de l'héroïne et fréquente le milieu de la petite criminalité. Sa dette envers le trafiquant serbe Milo l'incite à tenter un gros coup. Mais la police fait irruption pendant la transaction, et au cours de la poursuite qui s'ensuit, Frank perd à la fois la marchandise et l'argent. De rage, Frank expédie à l'hôpital son acolyte Tonny. Mais Milo commence à s'impatienter et se fait menaçant. ",
            genre: ['Action', 'Drama','Horror'],
            release_date: 1996,
            director: 'Nicolas Winding Refn',
            actors: 'Vanja Bajicic, Lisbeth Rasmussen, Levino Jensen',
            cover : 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjMwODk1MjA4NV5BMl5BanBnXkFtZTgwMjgwMzgwMzE@._V1_.jpg',
            upload_date: 19971223,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=dLEaPB9UBWM',
            downloadtime: 'Downloaded 234 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        },
        {
            id: 3,
            title: 'Paris, Texas',
            description : "Un homme réapparaît subitement après quatre années d'errance, période sur laquelle il ne donne aucune explication à son frère venu le retrouver. Ils partent pour Los Angeles récupérer le fils de l'ancien disparu, avec lequel celui-ci il part au Texas à la recherche de Jane, la mère de l'enfant. Une quête vers l'inconnu, une découverte mutuelle réunit,ces deux êtres au passé tourmenté.",
            genre: ['Drame', 'Comedy'],
            release_date: 1984,
            director: 'Wim Wenders',
            actors: 'Harry Dean Stanton, Nastassja Kinski, Hunter Carson',
            cover : 'http://www.notrecinema.com/images/cache/paris--texas-poster_482780_7902.jpg',
            upload_date: 20030616,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=HS_G7-JlucQ',
            downloadtime: 'Downloaded 456 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        },
        {
            id: 4,
            title: 'Fight Club',
            description : "Le narrateur, sans identité précise, vit seul, travaille seul, dort seul, mange seul ses plateaux-repas pour une personne comme beaucoup d'autres personnes seules qui connaissent la misère humaine, morale et sexuelle. C'est pourquoi il va devenir membre du Fight club, un lieu clandestin ou il va pouvoir retrouver sa virilité, l'échange et la communication. Ce club est dirigé par Tyler Durden, une sorte,d'anarchiste entre gourou et philosophe qui prêche l'amour de son prochain.",
            genre: ['Action','Drama'],
            release_date: 1999,
            director: 'Chuck Palahniuk',
            actors: 'Brad Pitt, Edward Norton, Helena Bonham Carter',
            cover : 'https://mindreels.files.wordpress.com/2014/08/fight-club-poster.jpg',
            upload_date: 20081216,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=N9_xlIN80rM',
            downloadtime: 'Downloaded 457 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        },
        {
            id: 5,
            title: 'Blue Velvet',
            description : "  Épaulée par son amie Sandy, Jeffrey, un jeune homme, mène son enquête concernant une oreille humaine trouvée dans un terrain vague. Il croise sur son chemin Dorothy Vallens, une mystérieuse chanteuse de cabaret.",
            genre: ['Drama'],
            release_date: 1987 ,
            director: 'David Lynch',
            actors: 'Isabella Rossellini, Kyle MacLachlan, Dennis Hopper',
            cover : 'http://fr.web.img5.acsta.net/pictures/14/01/09/10/34/294269.jpg',
            upload_date: 20010115,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=bWr4JvAWF20',
            downloadtime: 'Downloaded 276 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        },
        {
            id: 6,
            title: 'Forrest Gump',
            description : "Quelques décennies d'histoire américaine, des années 1940 à la fin du XXème siècle, à travers le regard et l'étrange odyssée d'un homme simple et pur, Forrest Gump.",
            genre: ['Drama'],
            release_date: 1994,
            director: 'Robert Zemeckis',
            actors: 'Tom Hanks, Gary Sinise, Robin Wright',
            cover : 'http://fr.web.img4.acsta.net/pictures/15/10/13/15/12/514297.jpg',
            upload_date: 20050323,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=vhbOdIJyalo',
            downloadtime: 'Downloaded 562 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        },
        {
            id: 7,
            title: 'Mulholland Drive',
            description : "A Hollywood, durant la nuit, Rita, une jeune femme, devient amnésique suite à un accident de voiture sur la route de Mulholland Drive. Elle fait la rencontre de Betty Elms, une actrice en devenir qui vient juste de débarquer à Los Angeles. Aidée par celle-ci, Rita tente de retrouver la mémoire ainsi que son identité.",
            genre: ['Drama'],
            release_date: 2001,
            director: 'David Lynch',
            actors: 'Naomi Watts, Laura Harring, Justin Theroux',
            cover : 'https://dbmoviesblog.files.wordpress.com/2012/01/mulholland-drive.jpg',
            upload_date: 19961223,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=XQ5Q0CHQ0EU',
            downloadtime: 'Downloaded 987 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        },
        {
            id: 8,
            title: 'Elle',
            description : "Michèle fait partie de ces femmes que rien ne semble atteindre. À la tête d'une grande entreprise de jeux vidéo, elle gère ses affaires comme sa vie sentimentale : d'une main de fer. Sa vie bascule lorsqu’elle est agressée chez elle par un mystérieux inconnu. Inébranlable, Michèle se met à le traquer en retour. Un jeu étrange s'installe alors entre eux. Un jeu qui, à tout instant, peut dégénérer.",
            genre: ['Drama','Thriller'],
            release_date: 2016,
            director: 'Paul Verhoeven',
            actors: 'Isabelle Huppert, Laurent Lafitte, Anne Consigny',
            cover : 'http://fr.web.img6.acsta.net/pictures/16/04/28/09/53/464442.jpg',
            upload_date: 20171126,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=YqGJtnKZ2vs',
            downloadtime: 'Downloaded 178 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        },
        {
            id: 9,
            title: 'Mademoiselle',
            description : "Corée. Années 30, pendant la colonisation japonaise. Une jeune femme (Sookee) est engagée comme servante d’une riche japonaise (Hideko), vivant recluse dans un immense manoir sous la coupe d’un oncle tyrannique. Mais Sookee a un secret. Avec l’aide d’un escroc se faisant passer pour un comte japonais, ils ont d’autres plans pour Hideko…",
            genre: ['Action'],
            release_date: 2016,
            director: 'Park Chan-Wook',
            actors: 'Kim Min-Hee, Kim Tae-Ri, Ha Jung-Woo',
            cover : 'http://fr.web.img4.acsta.net/r_1280_720/pictures/16/09/22/14/47/451429.jpg',
            upload_date: 20170001,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=40E5pL73yvM',
            downloadtime: 'Downloaded 273 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        },
        {
            id: 10,
            title: 'Independence Day 2',
            description : "Nous avons toujours su qu'ils reviendraient. La terre est menacée par une catastrophe d’une ampleur inimaginable. Pour la protéger, toutes les nations ont collaboré autour d’un programme de défense colossal exploitant la technologie extraterrestre récupérée. Mais rien ne peut nous préparer à la force de frappe sans précédent des aliens. Seule l'ingéniosité et le courage de quelques hommes et femmes peuvent sauver l’humanité de l'extinction.",
            genre: ['Action','Science-Fiction'],
            release_date: 2016,
            director: 'Roland Emmerich',
            actors: 'Liam Hemsworth, Jeff Goldblum, Bill Pullman',
            cover : 'http://fr.web.img2.acsta.net/pictures/16/05/26/09/17/421833.jpg',
            upload_date: 20170615,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=b577i7s2CiM',
            downloadtime: 'Downloaded 16000 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        }
    ]
}