export default function(){
    return[
        {
            id: 1,
            title: 'Game of Thrones',
            description : "Il y a très longtemps, à une époque oubliée, une force a détruit l'équilibre des saisons. Dans un pays où l'été peut durer plusieurs années et l'hiver toute une vie, des forces sinistres et surnaturelles se pressent aux portes du Royaume des Sept Couronnes. La confrérie de la Garde de Nuit, protégeant le Royaume de toute créature pouvant provenir d'au-delà du Mur protecteur, n'a plus les ressources nécessaires pour assurer la sécurité de tous. Après un été de dix années, un hiver rigoureux s'abat sur le Royaume avec la promesse d'un avenir des plus sombres. Pendant ce temps, complots et rivalités se jouent sur le continent pour s'emparer du Trône de Fer, le symbole du pouvoir absolu.",
            genre: ['Drama','Fantastic'],
            release_date: 2011,
            director: 'David Benioff',
            actors: 'Peter Dinklage, Nikolaj Coster-Waldau, Lena Headey',
            cover : 'http://fr.web.img5.acsta.net/pictures/15/12/01/15/35/063097.jpg',
            upload_date: 20110326,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=mLVmY8wO4Ic',
            downloadtime: 'Downloaded 201520 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        },
        {
            id: 2,
            title: 'Under The Dome',
            description : "Les habitants d’une petite communauté se réveillent un matin, coupés du monde et piégés dans la ville à cause d’un immense dôme transparent. Certains tenteront, de manière dissimulée, de tirer profit de cette situation inquiétante et inexpliquée, afin de prendre le pouvoir. Mais une résistance va s’organiser autour d'un vétéran de la guerre en Irak, pour empêcher ces personnes malveillantes de parvenir à leur fin.",
            genre: ['Drame'],
            release_date: 2013,
            director: 'Brian K. Vaughan',
            actors: 'Mike Vogel, Rachelle LeFevre, Dean Norris',
            cover : 'http://fractured-simplicity.net/daydreaming/gallery/albums/--/T-V/Under%20the%20Dome/002.jpg',
            upload_date: 20130101,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=uReJE04j3jc',
            downloadtime: 'Downloaded 789 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        },
        {
            id:3,
            title: 'Penny Dreadful',
            description : "Dans le Londres de l'époque Victorienne, Vanessa Ives, une jeune femme puissante aux pouvoirs hypnotiques, allie ses forces à celles d'Ethan, un garçon rebelle et violent aux allures de cowboy, et de Sir Malcolm, un vieil homme riche aux ressources inépuisables. Ensemble, ils combattent un ennemi inconnu, presque invisible, qui ne semble pas humain et qui massacre la population...",
            genre: ['Epouvante-Horreur'],
            release_date: 2014,
            director: 'John Logan' ,
            actors: 'Eva Green, Josh Hartnett, Timothy Dalton',
            cover : 'http://image.tmdb.org/t/p//original/irEp4Zp3cBcPHsCu3e1CqJqBf3b.jpg',
            upload_date: 20140124,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=uReJE04j3jc',
            downloadtime: 'Downloaded 871 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        },
        {
            id:4,
            title: 'True Blood',
            description : "Ayant trouvé un substitut pour se nourrir sans tuer (du sang synthétique), les vampires vivent désormais parmi les humains. Sookie, une serveuse capable de lire dans les esprits, tombe sous le charme de Bill, un mystérieux vampire. Une rencontre qui bouleverse la vie de la jeune femme...",
            genre: ['Fantastique'],
            release_date: 2008,
            director: 'Alan Ball',
            actors: 'Anna Paquin, Stephen Moyer, Ryan Kwanten',
            cover : 'http://vignette1.wikia.nocookie.net/trueblood/images/1/18/True_Blood_Saison_2.jpg/revision/latest?cb=20140409160109&path-prefix=fr',
            upload_date: 20081114,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=hE8wwYzKJOs',
            downloadtime: 'Downloaded 651 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
            },
        {
            id:5,
            title: 'Gotham',
            description : "Tout le monde connaît le Commissaire Gordon, valeureux adversaire des plus dangereux criminels, un homme dont la réputation rime avec loi et ordre. Mais que sait-on de son histoire ?",
            genre: ['Policier'],
            release_date: 2012,
            director: 'Michael Green',
            actors: 'Megan Ketch, Barry Sloane, Lennie James ',
            cover : 'http://seriesaddict.fr/images/galerie/originals/Gotham/Posters-saison-1/Gotham-Poster-Saison1-1.jpg',
            upload_date: 20121010,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=_1pgh2gPOus',
            downloadtime: 'Downloaded 593 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        },
        {
            id:6,
            title: 'Friends',
            description : "Les péripéties de 6 jeunes newyorkais liés par une profonde amitié. Entre amour, travail, famille, ils partagent leurs bonheurs et leurs soucis au Central Perk, leur café favori...",
            genre: ['Comédie'],
            release_date: 1994,
            director: 'Marta Kauffman, David Crane',
            actors: 'Jennifer Aniston, Courteney Cox, Lisa Kudrow',
            cover : 'https://str01-m.dpstream.media/s/8/friends-522501392b273-1472988623.jpg',
            upload_date: 19940912,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=hDNNmeeJs1Q',
            downloadtime: 'Downloaded 472 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        },
        {
            id:7,
            title: 'Arrow',
            description : "Les nouvelles aventures de Green Arrow/Oliver Queen, combattant ultra efficace issu de l'univers de DC Comics et surtout archer au talent fou, qui appartient notamment à la Justice League. Disparu en mer avec son père et sa petite amie, il est retrouvé vivant 5 ans plus tard sur une île près des côtes Chinoises. Mais il a changé : il est fort, courageux et déterminé à débarrasser Starling City de ses malfrats...",
            genre: ['Action'],
            release_date: 2012,
            director: 'Andrew Kreisberg',
            actors: 'Stephen Amell, David Ramsey, Willa Holland',
            cover : 'http://www.serie-stream.com/imgseries/arrowS1.jpg',
            upload_date: 20120520,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=nPCxc8vXMso',
            downloadtime: 'Downloaded 109 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        },
        {
            id:8,
            title: 'Vikings',
            description : "Scandinavie, à la fin du 8ème siècle. Ragnar Lodbrok, un jeune guerrier viking, est avide d'aventures et de nouvelles conquêtes. Lassé des pillages sur les terres de l'Est, il se met en tête d'explorer l'Ouest par la mer. Malgré la réprobation de son chef, Haraldson, il se fie aux signes et à la volonté des dieux, en construisant une nouvelle génération de vaisseaux, plus légers et plus rapides...",
            genre: ['Aventure'],
            release_date: 2013,
            director: 'Michael Hirst',
            actors: 'Travis Fimmel, Katheryn Winnick, Clive Standen',
            cover : 'http://marvelll.fr/wp-content/uploads/2014/03/Vikings-Saison-1-Affiche-Teaser.jpg',
            upload_date: 20130304,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=mAl60ykBm4A',
            downloadtime: 'Downloaded 408 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        },
        {
            id:9,
            title: 'Suits',
            description : "Avocat très ambitieux d'une grosse firme de Manhattan, Harvey Specter a besoin de quelqu'un pour l'épauler. Son choix se porte sur Mike Ross, un jeune homme très brillant mais sans diplôme, doté d'un talent certain et d'une mémoire photographique très précieuse.",
            genre: ['Comédie'],
            release_date: 2011,
            director: 'Aaron Korsh',
            actors: 'Patrick J. Adams, Gabriel Macht, Gina Torres',
            cover : 'https://1.bp.blogspot.com/-P3KcqoiIBfg/VaLDGq6wNzI/AAAAAAAAHcY/SknlDpxj05M/s1600/Suits.jpeg',
            upload_date: 20110420,
            uploader: 'thomas',
            youtube : 'hhttps://www.youtube.com/watch?v=mi1TR7S-0vQ',
            downloadtime: 'Downloaded 274 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        },
        {
            id: 10,
            title: 'Westworld',
            description: "A Westworld, un parc d'attractions dernier cri, les visiteurs paient des fortunes pour revivre le frisson de la conquête de l'Ouest. Dolores, Teddy et bien d'autres sont des androïdes à apparence humaine créés pour donner l'illusion et offrir du dépaysement aux clients. Pour ces derniers, Westworld est l'occasion de laisser libre-cours à leurs fantasmes",
            genre: ['Western'],
            release_date: 2016,
            director: 'Jonathan Nolan, Lisa Joy',
            actors: 'Evan Rachel Wood, Thandie Newton, Jeffrey Wright',
            cover: 'http://www.avcesar.com/source/actualites/00/00/4F/56/titre_094524.jpg',
            upload_date: 20140124,
            uploader: 'thomas',
            youtube: 'https://www.youtube.com/watch?v=h4cGPLjLNEQ',
            downloadtime: 'Downloaded 301 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        },
        {
            id: 11,
            title: 'The Walking dead',
            description : "Dans le Londres de l'époque Victorienne, Vanessa Ives, une jeune femme puissante aux pouvoirs hypnotiques, allie ses forces à celles d'Ethan, un garçon rebelle et violent aux allures de cowboy, et de Sir Malcolm, un vieil homme riche aux ressources inépuisables. Ensemble, ils combattent un ennemi inconnu, presque invisible, qui ne semble pas humain et qui massacre la population...",
            genre: ['Epouvante-Horreur'],
            release_date: 2010,
            director: 'Robert Kirkman',
            actors: 'Jeffrey Dean Morgan, Andrew Lincoln, Steven Yeun',
            cover : 'http://blaxup.com/upload/img/2015/10/dv25247ornwalkingdeads2_2015-10-21-14:55:10.jpg',
            upload_date: 20100110,
            uploader: 'thomas',
            youtube : 'https://www.youtube.com/watch?v=AbtiqJGhWyY',
            downloadtime: 'Downloaded 446 times',
            downloadlink: 'https://www.hadopi.fr/',
            downloadlinkHD: 'https://www.hadopi.fr/',
        }
]
}